In [7]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import (
    shapiro,
    levene,
    ttest_ind,
    mannwhitneyu,
    normaltest,
    median_test,
    t,
)
from cliffs_delta import cliffs_delta
import constants_pynb as const
from collections import Counter

In [8]:
metric_selection = [const.METRIC_NAME, const.TIMESTAP, const.METRIC_VALUE]
metric_row_selection = [
    const.DATA_SENT,
    const.DATA_RECEIVED,
    const.RESPONSE_SIZE,
    const.REPONSE_SIZE,
    const.RESPONSE_TIME,
    const.HTTP_REQ_DURATION,
]
metric_selection_pods = [const.PKG, const.OTHER]

In [9]:
# Create User
## Normal Report
json_create_user_1 = pd.read_csv(
    const.JSON_CREATE_USER_REPORT_PATH_1, usecols=metric_selection
)
json_create_user_1 = json_create_user_1[
    json_create_user_1[const.METRIC_NAME].isin(metric_row_selection)
]

json_create_user_2 = pd.read_csv(
    const.JSON_CREATE_USER_REPORT_PATH_2, usecols=metric_selection
)
json_create_user_2 = json_create_user_2[
    json_create_user_2[const.METRIC_NAME].isin(metric_row_selection)
]

json_create_user_3 = pd.read_csv(
    const.JSON_CREATE_USER_REPORT_PATH_3, usecols=metric_selection
)
json_create_user_3 = json_create_user_3[
    json_create_user_3[const.METRIC_NAME].isin(metric_row_selection)
]

## Pod Report
json_create_user_pod_1 = pd.read_csv(
    const.JSON_CREATE_USER_POD_REPORT_PATH_1, usecols=metric_selection_pods
)
json_create_user_pod_2 = pd.read_csv(
    const.JSON_CREATE_USER_POD_REPORT_PATH_2, usecols=metric_selection_pods
)
json_create_user_pod_3 = pd.read_csv(
    const.JSON_CREATE_USER_POD_REPORT_PATH_3, usecols=metric_selection_pods
)

# Get all Users
## Normal Report
json_get_all_users_1 = pd.read_csv(
    const.JSON_GET_ALL_USERS_REPORT_PATH_1, usecols=metric_selection
)
json_get_all_users_1 = json_get_all_users_1[
    json_get_all_users_1[const.METRIC_NAME].isin(metric_row_selection)
]

json_get_all_users_2 = pd.read_csv(
    const.JSON_GET_ALL_USERS_REPORT_PATH_2, usecols=metric_selection
)
json_get_all_users_2 = json_get_all_users_2[
    json_get_all_users_2[const.METRIC_NAME].isin(metric_row_selection)
]

json_get_all_users_3 = pd.read_csv(
    const.JSON_GET_ALL_USERS_REPORT_PATH_3, usecols=metric_selection
)
json_get_all_users_3 = json_get_all_users_3[
    json_get_all_users_3[const.METRIC_NAME].isin(metric_row_selection)
]

## Pod Report
json_get_all_users_pod_1 = pd.read_csv(
    const.JSON_GET_ALL_USERS_POD_REPORT_PATH_1, usecols=metric_selection_pods
)
json_get_all_users_pod_2 = pd.read_csv(
    const.JSON_GET_ALL_USERS_POD_REPORT_PATH_2, usecols=metric_selection_pods
)
json_get_all_users_pod_3 = pd.read_csv(
    const.JSON_GET_ALL_USERS_POD_REPORT_PATH_3, usecols=metric_selection_pods
)
# Get User by ID
## Normal Report
json_get_user_id_1 = pd.read_csv(
    const.JSON_GET_USER_ID_REPORT_PATH_1, usecols=metric_selection
)
json_get_user_id_1 = json_get_user_id_1[
    json_get_user_id_1[const.METRIC_NAME].isin(metric_row_selection)
]

json_get_user_id_2 = pd.read_csv(
    const.JSON_GET_USER_ID_REPORT_PATH_2, usecols=metric_selection
)
json_get_user_id_2 = json_get_user_id_2[
    json_get_user_id_2[const.METRIC_NAME].isin(metric_row_selection)
]

json_get_user_id_3 = pd.read_csv(
    const.JSON_GET_USER_ID_REPORT_PATH_3, usecols=metric_selection
)
json_get_user_id_3 = json_get_user_id_3[
    json_get_user_id_3[const.METRIC_NAME].isin(metric_row_selection)
]

## Pod Report
json_get_user_id_pod_1 = pd.read_csv(
    const.JSON_GET_USER_ID_POD_REPORT_PATH_1, usecols=metric_selection_pods
)
json_get_user_id_pod_2 = pd.read_csv(
    const.JSON_GET_USER_ID_POD_REPORT_PATH_2, usecols=metric_selection_pods
)
json_get_user_id_pod_3 = pd.read_csv(
    const.JSON_GET_USER_ID_POD_REPORT_PATH_3, usecols=metric_selection_pods
)
# Get all Products entities
## Normal Report
json_get_all_product_entities_1 = pd.read_csv(
    const.JSON_GET_ALL_PRODUCT_ENTITIES_REPORT_PATH_1, usecols=metric_selection
)
json_get_all_product_entities_1 = json_get_all_product_entities_1[
    json_get_all_product_entities_1[const.METRIC_NAME].isin(metric_row_selection)
]

json_get_all_product_entities_2 = pd.read_csv(
    const.JSON_GET_ALL_PRODUCT_ENTITIES_REPORT_PATH_2, usecols=metric_selection
)
json_get_all_product_entities_2 = json_get_all_product_entities_2[
    json_get_all_product_entities_2[const.METRIC_NAME].isin(metric_row_selection)
]

json_get_all_product_entities_3 = pd.read_csv(
    const.JSON_GET_ALL_PRODUCT_ENTITIES_REPORT_PATH_3, usecols=metric_selection
)
json_get_all_product_entities_3 = json_get_all_product_entities_3[
    json_get_all_product_entities_3[const.METRIC_NAME].isin(metric_row_selection)
]

## Pod Report
json_get_all_product_entities_pod_1 = pd.read_csv(
    const.JSON_GET_ALL_PRODUCT_ENTITIES_POD_REPORT_PATH_1, usecols=metric_selection_pods
)
json_get_all_product_entities_pod_2 = pd.read_csv(
    const.JSON_GET_ALL_PRODUCT_ENTITIES_POD_REPORT_PATH_2, usecols=metric_selection_pods
)
json_get_all_product_entities_pod_3 = pd.read_csv(
    const.JSON_GET_ALL_PRODUCT_ENTITIES_POD_REPORT_PATH_3, usecols=metric_selection_pods
)

# Create User
## Normal Report
protobuf_create_user_1 = pd.read_csv(
    const.PROTOBUF_CREATE_USER_REPORT_PATH_1, usecols=metric_selection
)
protobuf_create_user_1 = protobuf_create_user_1[
    protobuf_create_user_1[const.METRIC_NAME].isin(metric_row_selection)
]

protobuf_create_user_2 = pd.read_csv(
    const.PROTOBUF_CREATE_USER_REPORT_PATH_2, usecols=metric_selection
)
protobuf_create_user_2 = protobuf_create_user_2[
    protobuf_create_user_2[const.METRIC_NAME].isin(metric_row_selection)
]

protobuf_create_user_3 = pd.read_csv(
    const.PROTOBUF_CREATE_USER_REPORT_PATH_3, usecols=metric_selection
)
protobuf_create_user_3 = protobuf_create_user_3[
    protobuf_create_user_3[const.METRIC_NAME].isin(metric_row_selection)
]

## Pod Report
protobuf_create_user_pod_1 = pd.read_csv(
    const.PROTOBUF_CREATE_USER_POD_REPORT_PATH_1, usecols=metric_selection_pods
)
protobuf_create_user_pod_2 = pd.read_csv(
    const.PROTOBUF_CREATE_USER_POD_REPORT_PATH_2, usecols=metric_selection_pods
)
protobuf_create_user_pod_3 = pd.read_csv(
    const.PROTOBUF_CREATE_USER_POD_REPORT_PATH_3, usecols=metric_selection_pods
)

# Get all Users
## Normal Report
protobuf_get_all_users_1 = pd.read_csv(
    const.PROTOBUF_GET_ALL_USERS_REPORT_PATH_1, usecols=metric_selection
)
protobuf_get_all_users_1 = protobuf_get_all_users_1[
    protobuf_get_all_users_1[const.METRIC_NAME].isin(metric_row_selection)
]

protobuf_get_all_users_2 = pd.read_csv(
    const.PROTOBUF_GET_ALL_USERS_REPORT_PATH_2, usecols=metric_selection
)
protobuf_get_all_users_2 = protobuf_get_all_users_2[
    protobuf_get_all_users_2[const.METRIC_NAME].isin(metric_row_selection)
]

protobuf_get_all_users_3 = pd.read_csv(
    const.PROTOBUF_GET_ALL_USERS_REPORT_PATH_3, usecols=metric_selection
)
protobuf_get_all_users_3 = protobuf_get_all_users_3[
    protobuf_get_all_users_3[const.METRIC_NAME].isin(metric_row_selection)
]

## Pod Report
protobuf_get_all_users_pod_1 = pd.read_csv(
    const.PROTOBUF_GET_ALL_USERS_POD_REPORT_PATH_1, usecols=metric_selection_pods
)
protobuf_get_all_users_pod_2 = pd.read_csv(
    const.PROTOBUF_GET_ALL_USERS_POD_REPORT_PATH_2, usecols=metric_selection_pods
)
protobuf_get_all_users_pod_3 = pd.read_csv(
    const.PROTOBUF_GET_ALL_USERS_POD_REPORT_PATH_3, usecols=metric_selection_pods
)
# Get User by ID
## Normal Report
protobuf_get_user_id_1 = pd.read_csv(
    const.PROTOBUF_GET_USER_ID_REPORT_PATH_1, usecols=metric_selection
)
protobuf_get_user_id_1 = protobuf_get_user_id_1[
    protobuf_get_user_id_1[const.METRIC_NAME].isin(metric_row_selection)
]

protobuf_get_user_id_2 = pd.read_csv(
    const.PROTOBUF_GET_USER_ID_REPORT_PATH_2, usecols=metric_selection
)
protobuf_get_user_id_2 = protobuf_get_user_id_2[
    protobuf_get_user_id_2[const.METRIC_NAME].isin(metric_row_selection)
]

protobuf_get_user_id_3 = pd.read_csv(
    const.PROTOBUF_GET_USER_ID_REPORT_PATH_3, usecols=metric_selection
)
protobuf_get_user_id_3 = protobuf_get_user_id_3[
    protobuf_get_user_id_3[const.METRIC_NAME].isin(metric_row_selection)
]

## Pod Report
protobuf_get_user_id_pod_1 = pd.read_csv(
    const.PROTOBUF_GET_USER_ID_POD_REPORT_PATH_1, usecols=metric_selection_pods
)
protobuf_get_user_id_pod_2 = pd.read_csv(
    const.PROTOBUF_GET_USER_ID_POD_REPORT_PATH_2, usecols=metric_selection_pods
)
protobuf_get_user_id_pod_3 = pd.read_csv(
    const.PROTOBUF_GET_USER_ID_POD_REPORT_PATH_3, usecols=metric_selection_pods
)

# Get all Products entities
## Normal Report
protobuf_get_all_product_entities_1 = pd.read_csv(
    const.PROTOBUF_GET_ALL_PRODUCT_ENTITIES_REPORT_PATH_1, usecols=metric_selection
)
protobuf_get_all_product_entities_1 = protobuf_get_all_product_entities_1[
    protobuf_get_all_product_entities_1[const.METRIC_NAME].isin(metric_row_selection)
]

protobuf_get_all_product_entities_2 = pd.read_csv(
    const.PROTOBUF_GET_ALL_PRODUCT_ENTITIES_REPORT_PATH_2, usecols=metric_selection
)
protobuf_get_all_product_entities_2 = protobuf_get_all_product_entities_2[
    protobuf_get_all_product_entities_2[const.METRIC_NAME].isin(metric_row_selection)
]

protobuf_get_all_product_entities_3 = pd.read_csv(
    const.PROTOBUF_GET_ALL_PRODUCT_ENTITIES_REPORT_PATH_3, usecols=metric_selection
)
protobuf_get_all_product_entities_3 = protobuf_get_all_product_entities_3[
    protobuf_get_all_product_entities_3[const.METRIC_NAME].isin(metric_row_selection)
]

## Pod Report
protobuf_get_all_product_entities_pod_1 = pd.read_csv(
    const.PROTOBUF_GET_ALL_PRODUCT_ENTITIES_POD_REPORT_PATH_1,
    usecols=metric_selection_pods,
)
protobuf_get_all_product_entities_pod_2 = pd.read_csv(
    const.PROTOBUF_GET_ALL_PRODUCT_ENTITIES_POD_REPORT_PATH_2,
    usecols=metric_selection_pods,
)
protobuf_get_all_product_entities_pod_3 = pd.read_csv(
    const.PROTOBUF_GET_ALL_PRODUCT_ENTITIES_POD_REPORT_PATH_3,
    usecols=metric_selection_pods,
)

In [ ]:

def extract_response_times(df, metric_col, value_col, target_metric):
    return df[df[metric_col] == target_metric][value_col].values
def calculate_throughput(timestamps):
    timestamp_counts = Counter(timestamps)
    throughput_array = np.zeros(len(timestamps))

    for i, ts in enumerate(timestamps):
        throughput_array[i] = timestamp_counts[ts]

    # Calculate mean throughput
    mean_throughput = round(np.mean(throughput_array),2)

    return throughput_array, mean_throughput

In [18]:
timestamps_1= extract_response_times(
    json_create_user_1, const.METRIC_NAME, const.TIMESTAP, const.HTTP_REQ_DURATION
)


throughput_array_1, mean_throughput_1 = calculate_throughput(timestamps_1)
print(mean_throughput_1)
print(throughput_array_1)

timestamps_2= extract_response_times(
    json_create_user_2, const.METRIC_NAME, const.TIMESTAP, const.HTTP_REQ_DURATION
)

throughput_array_2, mean_throughput_2 = calculate_throughput(timestamps_2)
print(mean_throughput_2)
print(throughput_array_2)

timestamps_3= extract_response_times(
    json_create_user_3, const.METRIC_NAME, const.TIMESTAP, const.HTTP_REQ_DURATION
)

throughput_array_3, mean_throughput_3 = calculate_throughput(timestamps_3)
print(mean_throughput_3)
print(throughput_array_3)

5.25
[5. 5. 5. ... 6. 6. 6.]
5.02
[4. 4. 4. ... 5. 2. 2.]
4.8
[2. 2. 4. ... 5. 2. 2.]
